### ISSUE TITLE
color scheme given distributions are difficult to distinguish for non-colorblind 

### ISSUE THREAD

**Issue by trashbirdecology** [sdtaylor/FederalJobs#1]
given the skewed distribution of the data in most of the maps/pngs, the colors are difficult to distinguish under many of the color blind filters. consider different color scheme to make those differences between darks much more obvious, esp for monochromacy

**Comment by sdtaylor** [comment]
good catch. the yellow in viridis actually bleeds with white in some cases. I switched it to this

![image](https://user-images.githubusercontent.com/12282062/114958695-c79c8d80-9e20-11eb-9bc6-c7dabf3ad25d.png)

**Comment by trashbirdecology** [comment]
nice palette!

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data Integration <https://www.usgs.gov/centers/cdi>! All
welcome. It's cool.
