### ISSUE TITLE
add Google Doc links to repo readme

### ISSUE THREAD

**Issue by trashbirdecology** [sdtaylor/FederalJobs#3]
Suggest adding a link to the GDOC in repo readme. 

https://docs.google.com/document/d/15ylkL0gIAf5vlrS5-T87MJoO9x52uqroV_9acWQmn6A/edit

**Comment by sdtaylor** [comment]
👍 done. https://github.com/sdtaylor/FederalJobs/commit/8548d81390cac6e427339dcd1f3dbdbd609e3fc4
